version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - web-network
    depends_on:
      - php
      - mariadb

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./html:/var/www/html
    networks:
      - web-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: monsite
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - web-network
    depends_on:
      - mariadb


networks:
  web-network:
    driver: bridge

volumes:
  db-data:
