version: '3.8'

services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
      - nginx-logs:/tmp
    networks:
      - web-network
    depends_on:
      - php
      - mariadb

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./html:/var/www/html
      - nginx-logs:/tmp
    networks:
      - web-network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: monsite
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - web-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: secret
    networks:
      - web-network
    depends_on:
      - mariadb

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - '0.0.0.0:8081:8080'
    volumes:
      - /:/rootfs:roS
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped


networks:
  web-network:
    driver: bridge

volumes:
  db-data:
  nginx-logs:
