server {
	listen 80;
	server_name localhost;
	return 301 https://$host$request_uri;
}

server {
	listen 443 ssl;
	server_name localhost;

	ssl_certificate /etc/nginx/ssl/ssl.crt;
	ssl_certificate_key /etc/nginx/ssl/ssl.key;

	root /usr/share/nginx/html;
	index index.html index.php;

	access_log /tmp/access.log;
	error_log /tmp/error.log;

	location / {
		try_files $uri $uri/ =404;
	}

	location ~ \.php$ {
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
	}
}
